name: Gentx Format
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  verify-gentx:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: gentx-validation
        run: |
          bash -x ./scripts/validate-gentxs.sh
        env:
          DAEMON: evmosd
          CHAIN_ID: evmos_9000-2
          GOPATH: ${{ github.workspace }}
          DENOM: aphoton
          GH_URL: https://github.com/tharsis/evmos
          BINARY_VERSION: v0.2.0
          GO_VERSION: 1.17
          PRELAUNCH_GENESIS_URL: https://raw.githubusercontent.com/tharsis/testnets/main/olympus_mons/genesis.json
          GENTXS_DIR: ${{ github.workspace }}/github.com/tharsis/testnets/olympus_mons/gentxs